steps:
  - id: Initiate gcloud
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - '-c'
      - |
          gcloud config set project ${PROJECT_ID}
          gcloud config set compute/region ${_PROJECT_REGION}

  - id: Build and deploy firebase
    name: node:10.22-alpine
    entrypoint: sh
    args:
      - '-c'
      - |
          # npm install -g firebase-tools
          # npm install --save firebase-functions@latest
          # npm install -g tslint

          ls -la

          # firebase deploy --only firestore:rules --project=${PROJECT_ID} --token=${_FIREBASE_TOKEN}

          # cd ./functions
          # npm install

          # npm run build
          # firebase deploy --only functions --project=${PROJECT_ID} --token=${_FIREBASE_TOKEN}
