steps:
  - id: Initiate gcloud
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - '-c'
      - |
          gcloud config set project ${PROJECT_ID}
          gcloud config set compute/region ${_PROJECT_REGION}

  - id: Build and deploy firebase
    name: node:10.22-alpine
    entrypoint: sh
    args:
      - '-c'
      - |
          npm cache clean --force
          npm i -g firebase-tools
          npm i firebase-functions@latest
          npm i -g tslint

          firebase deploy --only firestore:rules --project=${PROJECT_ID} --token=${_FIREBASE_TOKEN}

          cd ./functions
          npm i

          npm run build
          firebase deploy --only functions --project=${PROJECT_ID} --token=${_FIREBASE_TOKEN}
