steps:
  # Build base image
  # Install node modules
  # Run linter
  - name: 'node:10.22-alpine'
    entrypoint: sh
    args:
      - '-c'
      - |
          npm install -g firebase-tools
          npm install -g tslint
          npm install
          npm run build
    
  # Deploy cloud functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'mpesaMain', '--project', '$_PROJECT_NAME','--trigger-http','--runtime','nodejs10','--source','.']