name: water_del
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  provider: 
  google_maps_flutter: ^0.5.27+3
  # Permissions
  permission_handler: ^3.1.0
  # Location
  location: ^2.3.5
  # Spin Kit
  flutter_spinkit: 
  # Bottom Sheet
  solid_bottom_sheet: ^0.1.9

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
