name: water_del
description: A new Flutter project.

publish_to: 'none'

version: 1.0.7+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bottom_navy_bar: ^5.4.0
  google_fonts:
  provider: 
  firebase_auth:
  firebase_analytics:
  cloud_firestore:
  firebase_messaging:
  firebase_crashlytics:
  firebase_storage:
  image_picker:
  firebase_performance: 
  google_sign_in:
  google_maps_flutter: ^0.5.27+3
  permission_handler: ^3.1.0
  location: ^2.3.5
  flutter_spinkit: 
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter:

  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/launcher/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/waterdel.png"
  image_path_android: "assets/launcher/waterdel.png"
  # adaptive_icon_background: "assets/launcher/waterdel.png"
  # adaptive_icon_foreground: "assets/launcher/waterdel.png"
