name: water_del
description: A new Flutter project.

publish_to: "none"

version: 1.0.15+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_size_text: null
  bottom_navy_bar: ^5.4.0
  cached_network_image: 2.5.1
  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^0.1.3
  firebase_analytics: ^6.0.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_crashlytics: ^0.2.1+1
  firebase_messaging: ^7.0.3
  firebase_performance: ^0.4.0+2
  firebase_storage: ^4.0.1
  floating_action_bubble: null
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.1
  font_awesome_flutter: null
  geolocator: null
  google_fonts: ^1.1.1
  google_maps_flutter: ^0.5.27+3
  google_sign_in: ^4.5.5
  image_picker: ^0.6.7+12
  intl: ^0.16.1
  location: ^2.3.5
  lottie: ^0.5.1
  page_transition: null
  permission_handler: ^3.1.0
  provider: ^4.3.2+2
  timeago: null
  url_launcher: null
dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/lottie/
    - assets/images/
    - assets/launcher/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/waterdel.png"
  image_path_android: "assets/launcher/waterdel.png"
