name: Build and Release APK
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - run: flutter pub get
    # - run: flutter test --> Uncomment this line IF testing has been implemented
    - run: flutter build apk --shrink --target-platform android-arm

    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      with:
        commit: master
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
        tag: v1.1.${{ github.run_number }}

    - name: Upload APK on Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: build/app/outputs/apk/release/app-release.apk
        
    - name: Upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: admins
        file: build/app/outputs/apk/release/app-release.apk